import mongoose from 'mongoose';

const alertSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true
  },
  type: {
    type: String,
    required: true
  },
  severity: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium'
  },
  location: {
    type: {
      type: String,
      enum: ['Point'],
      required: true,
      default: 'Point'
    },
    coordinates: {
      type: [Number], // [longitude, latitude]
      required: true,
      default: [0, 0]
    },
    address: String,
    city: String,
    state: String
  },
  message: {
    type: String,
    default: ""
  },
  description: {
    type: String,
    required: true
  },
  safetyInstructions: {
    type: String,
    default: ""
  },
  status: {
    type: String,
    enum: ['active', 'resolved'],
    default: 'active'
  },
  source: {
    type: String,
    enum: ['sensor', 'admin', 'auto-ai'],
    default: 'admin'
  },
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Indexing
alertSchema.index({ location: '2dsphere' });

const Alert = mongoose.model('Alert', alertSchema);

export default Alert;
