import mongoose from 'mongoose';

const requestDispatchSchema = new mongoose.Schema(
  {
    teamId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Team',
      required: false
    },
    teamName: {
      type: String,
      default: ""
    },
    memberCount: {
      type: Number,
      default: 0
    },
    members: {
      type: [String],
      default: []
    },
    memberPhones: {
      type: [String],
      default: []
    },
    leadPhone: {
      type: String,
      default: ""
    },
    eta: {
      type: String,
      default: ""
    },
    distance: {
      type: String,
      default: ""
    },
    status: {
      type: String,
      default: ""
    },
    autoGenerated: {
      type: Boolean,
      default: false
    },
    lastUpdatedAt: {
      type: Date,
      default: Date.now
    }
  },
  { _id: false }
);

const requestSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  name: { type: String, required: true },
  phone: String,
  peopleCount: {
    type: Number,
    default: 1
  },
  description: { type: String, required: true },
  emergencyType: {
    type: String,
    default: "other"
  },
  priority: { type: String, enum: ['low', 'medium', 'high', 'critical'], default: 'medium' },
  status: { type: String, enum: ['pending', 'assigned', 'resolved', 'cancelled'], default: 'pending' },
  assignedTeam: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Team',
    required: false
  },
  dispatch: {
    type: requestDispatchSchema,
    default: () => ({})
  },
  location: {
    address: String,
    city: String,
    state: String,
    lat: Number,
    lng: Number
  },
  createdAt: { type: Date, default: Date.now }
});

const Request = mongoose.model('Request', requestSchema);

export default Request;
