import mongoose from 'mongoose';

const sosSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: false
  },
  message: {
    type: String,
    required: true
  },
  emergencyType: {
    type: String,
    enum: ['flood', 'fire', 'medical', 'earthquake', 'rescue', 'accident', 'other'],
    default: 'other'
  },
  location: {
    type: {
      type: String,
      enum: ['Point'],
      required: true,
      default: 'Point'
    },
    coordinates: {
      type: [Number], // [longitude, latitude]
      required: true,
      default: [0, 0]
    },
    address: String
  },
  peopleCount: {
    type: Number,
    default: 1
  },
  status: {
    type: String,
    enum: ['active', 'acknowledged', 'dispatched', 'resolved', 'spam'],
    default: 'active'
  },
  spamScore: {
    type: Number,
    min: 0,
    max: 100,
    default: 0
  },
  aiDetectedIntent: {
    type: String,
    default: ""
  },
  autoReplySent: {
    type: Boolean,
    default: false
  },
  dispatch: {
    teamId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Team',
      required: false
    },
    teamName: {
      type: String,
      default: ""
    },
    memberCount: {
      type: Number,
      default: 0
    },
    members: {
      type: [String],
      default: []
    },
    memberPhones: {
      type: [String],
      default: []
    },
    leadPhone: {
      type: String,
      default: ""
    },
    eta: {
      type: String,
      default: ""
    },
    distance: {
      type: String,
      default: ""
    },
    status: {
      type: String,
      default: ""
    },
    autoGenerated: {
      type: Boolean,
      default: false
    },
    lastUpdatedAt: {
      type: Date,
      default: Date.now
    }
  },
  media: [String], // Array of URLs
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Indexing
sosSchema.index({ location: '2dsphere' });
sosSchema.index({ status: 1 });
sosSchema.index({ createdAt: 1 });

const SOS = mongoose.model('SOS', sosSchema);

export default SOS;
