import mongoose from 'mongoose';

const hashString = (value = "") =>
  Array.from(String(value)).reduce((acc, char) => acc + char.charCodeAt(0), 0);

const buildFallbackPhone = (seed, index = 0) => {
  const hashed = String(100000000 + ((hashString(seed) + index * 7919) % 900000000)).padStart(9, "0");
  return `+91 9${hashed}`;
};

const teamSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true
  },
  capacity: {
    type: Number,
    required: true
  },
  status: {
    type: String,
    enum: ['AVAILABLE', 'DISPATCHED', 'INACTIVE'],
    default: 'AVAILABLE'
  },
  specialization: {
    type: String,
    enum: ['general', 'flood', 'fire', 'medical', 'earthquake', 'urban_search', 'hazmat'],
    default: 'general'
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  currentLocation: {
    type: {
      type: String,
      enum: ['Point'],
      default: 'Point'
    },
    coordinates: {
      type: [Number],
      default: [0, 0] // [lng, lat]
    }
  },
  memberCount: {
    type: Number,
    default: 0
  },
  memberNames: {
    type: [String],
    default: []
  },
  memberPhones: {
    type: [String],
    default: []
  },
  leadName: {
    type: String,
    default: ""
  },
  leadPhone: {
    type: String,
    default: ""
  },

  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Create index for geospatial searches (e.g., nearest team)
teamSchema.index({ currentLocation: '2dsphere' });

/**
 * Pre-validate hook:
 * - If admin provides real memberNames/memberPhones → use them as-is.
 * - If autoGenerated and no member data provided → generate fallback names/phones.
 * - Always sync memberCount, leadPhone, leadName from member arrays.
 */
teamSchema.pre('validate', function () {
  const safeName = this.name || "Rescue Team";

  // Ensure arrays
  if (!Array.isArray(this.memberNames)) this.memberNames = [];
  if (!Array.isArray(this.memberPhones)) this.memberPhones = [];

  // Clean empty strings from arrays
  this.memberNames = this.memberNames.filter(n => typeof n === 'string' && n.trim().length > 0);
  this.memberPhones = this.memberPhones.filter(p => typeof p === 'string' && p.trim().length > 0);

  // Only auto-generate if no real member data was provided
  const hasRealMembers = this.memberNames.length > 0;

  if (!hasRealMembers) {
    // Auto-generate fallback names based on capacity
    const desiredCount = Math.max(
      Math.min(this.capacity || 1, 6),
      1
    );
    this.memberNames = Array.from(
      { length: desiredCount },
      (_, index) => `${safeName} Member ${index + 1}`
    );
    this.autoGenerated = this.autoGenerated || this.memberNames.every(
      (n) => n.includes("Member ")
    );
  }

  // Pad phones to match member count — only generate missing ones
  if (this.memberPhones.length < this.memberNames.length) {
    this.memberPhones = this.memberNames.map(
      (_member, index) =>
        this.memberPhones[index] || buildFallbackPhone(`${safeName}-${index + 1}`, index)
    );
  }

  // Trim extra phones if more phones than members
  if (this.memberPhones.length > this.memberNames.length) {
    this.memberPhones = this.memberPhones.slice(0, this.memberNames.length);
  }

  // Sync computed fields
  this.memberCount = this.memberNames.length;
  this.leadName = this.leadName || this.memberNames[0] || "";
  this.leadPhone = this.leadPhone || this.memberPhones[0] || "";
});

const Team = mongoose.model('Team', teamSchema);

export default Team;
