import Team from "../models/Team.js";
import { haversineDistanceKm } from "../utils/haversine.js";

const AVERAGE_SPEED_KMH = 40;

const TEAM_LIBRARY = {
  flood: [
    { name: "River Shield Unit", members: ["Aman", "Ravi", "Karan", "Sahil"] },
    { name: "Rapid Boat Team", members: ["Imran", "Vikas", "Nitin", "Yash"] },
  ],
  fire: [
    { name: "Fire Response Squad", members: ["Vivek", "Arjun", "Kabir", "Neeraj"] },
    { name: "Smoke Control Team", members: ["Harsh", "Ankit", "Rohit", "Deepak"] },
  ],
  medical: [
    { name: "Medical Rescue Unit", members: ["Dr. Meera", "Nurse Kavya", "Paramedic Rohan"] },
    { name: "Trauma Support Team", members: ["Dr. Arjun", "Nurse Pooja", "Paramedic Keshav"] },
  ],
  earthquake: [
    { name: "Urban Search Team", members: ["Aditya", "Manish", "Lokesh", "Pratik"] },
    { name: "Collapsed Structure Unit", members: ["Jatin", "Suraj", "Vinay", "Dheeraj"] },
  ],
  other: [
    { name: "General Rescue Team", members: ["Rahul", "Akash", "Dev", "Mohan"] },
  ],
};

const hashString = (value = "") =>
  Array.from(String(value)).reduce((acc, char) => acc + char.charCodeAt(0), 0);

const generatePhoneNumber = (seed = "", index = 0) => {
  const hashed = String(100000000 + ((hashString(seed) + index * 7919) % 900000000)).padStart(9, "0");
  return `+91 9${hashed}`;
};

const createTeamPayload = ({ emergencyType, peopleCount, sosCoords }) => {
  const library = TEAM_LIBRARY[emergencyType] || TEAM_LIBRARY.other;
  const template = library[hashString(`${emergencyType}-${peopleCount}`) % library.length];
  const [lng, lat] = sosCoords;
  const members = template.members.slice(0, Math.max(3, Math.min(Number(peopleCount) + 2, 6)));
  const memberPhones = members.map((member, index) =>
    generatePhoneNumber(`${template.name}-${member}-${lat}-${lng}`, index)
  );

  return {
    name: `${template.name} ${String(Date.now()).slice(-4)}`,
    capacity: Math.max(Number(peopleCount) + 1, members.length),
    status: "AVAILABLE",
    specialization: emergencyType || "general",
    autoGenerated: true,
    currentLocation: {
      type: "Point",
      coordinates: [Number(lng) + 0.02, Number(lat) + 0.02],
    },
    memberCount: members.length,
    memberNames: members,
    memberPhones,
    leadPhone: memberPhones[0] || "",
  };
};

const formatDispatchInfo = (team, distanceKm) => {
  const etaMinutes = Math.max(3, Math.round((distanceKm / AVERAGE_SPEED_KMH) * 60));
  const etaText = etaMinutes <= 5 ? "3-5 minutes" : `${etaMinutes - 2}-${etaMinutes + 3} minutes`;

  return {
    dispatched: true,
    teamId: team._id,
    team: {
      id: team._id,
      name: team.name,
      memberCount: team.memberCount || team.memberNames?.length || 0,
      members: team.memberNames || [],
      memberPhones: team.memberPhones || [],
      leadPhone: team.leadPhone || team.memberPhones?.[0] || "",
      distance: `${distanceKm.toFixed(1)} km`,
      status: "EN_ROUTE",
      autoGenerated: Boolean(team.autoGenerated),
    },
    eta: etaText,
    distance: `${distanceKm.toFixed(1)} km`,
  };
};

const ensureAvailableTeam = async ({
  availableTeams,
  emergencyType,
  peopleCount,
  sosCoords,
  io,
  sosId,
  requestId,
  mode = "sos",
}) => {
  if (availableTeams?.length) {
    return availableTeams;
  }

  const generatedTeam = await Team.create(
    createTeamPayload({ emergencyType, peopleCount, sosCoords })
  );

  if (io) {
    io.to("admin_room").emit("team_generated", {
      sosId,
      requestId,
      mode,
      teamId: generatedTeam._id,
      teamName: generatedTeam.name,
      autoGenerated: true,
      message: `Auto-generated backup rescue team "${generatedTeam.name}" is now available.`,
    });
  }

  return [generatedTeam];
};

const emitDispatchEvents = ({
  io,
  mode,
  selectedTeam,
  dispatchInfo,
  userLocation,
  userId,
  sosId,
  requestId,
  emergencyType,
}) => {
  if (!io) return;

  const [teamLng, teamLat] = selectedTeam.currentLocation?.coordinates || [0, 0];
  const basePayload = {
    message:
      mode === "request"
        ? `Help request assigned to team "${selectedTeam.name}".`
        : `Help is on the way. Team "${selectedTeam.name}" dispatched.`,
    teamId: String(selectedTeam._id),
    teamName: selectedTeam.name,
    memberCount: dispatchInfo.team.memberCount,
    members: dispatchInfo.team.members,
    memberPhones: dispatchInfo.team.memberPhones,
    leadPhone: dispatchInfo.team.leadPhone,
    eta: dispatchInfo.eta,
    distance: dispatchInfo.distance,
    status: dispatchInfo.team.status,
    autoGenerated: dispatchInfo.team.autoGenerated,
    teamLocation: selectedTeam.currentLocation,
    lat: teamLat,
    lng: teamLng,
  };

  if (mode === "request") {
    const requestPayload = {
      ...basePayload,
      requestId,
      emergencyType,
    };

    if (userId) {
      io.to(`user_${userId}`).emit("request_team_assigned", requestPayload);
    }
    io.to("admin_room").emit("request_team_assigned", requestPayload);
    io.emit("request_team_assigned", requestPayload);
  } else {
    const sosPayload = {
      ...basePayload,
      sosId,
    };

    if (userId) {
      io.to(`user_${userId}`).emit("sos_dispatched", sosPayload);
    }
    io.emit("sos_dispatched", sosPayload);
    io.to("admin_room").emit("mission_created", {
      sosId,
      teamId: selectedTeam._id,
      teamName: selectedTeam.name,
      emergencyType,
      status: "IN_PROGRESS",
      autoGenerated: dispatchInfo.team.autoGenerated,
    });
  }

  io.emit("team_location_update", {
    teamId: String(selectedTeam._id),
    teamName: selectedTeam.name,
    status: "DISPATCHED",
    lat: teamLat,
    lng: teamLng,
    destination: userLocation,
    currentLocation: selectedTeam.currentLocation,
  });
  io.emit("stats.updated", { type: `${mode}_dispatch` });
};

const dispatchNearestTeam = async ({
  userLocation,
  emergencyType,
  peopleCount = 1,
  sosId,
  requestId,
  io = null,
  userId = null,
  mode = "sos",
}) => {
  const targetLabel = mode === "request" ? `REQUEST-${requestId}` : `SOS-${sosId}`;
  console.log(`[DISPATCH] Searching nearest team for ${emergencyType} ${targetLabel} (${peopleCount} people)...`);

  const sosCoords = userLocation?.coordinates;
  if (!sosCoords || sosCoords.length < 2) {
    console.log("[DISPATCH] Invalid SOS coordinates.");
    return { dispatched: false, reason: "invalid_coordinates" };
  }

  let availableTeams;
  try {
    availableTeams = await Team.find({
      status: "AVAILABLE",
      currentLocation: {
        $near: {
          $geometry: { type: "Point", coordinates: sosCoords },
          $maxDistance: 100_000,
        },
      },
    }).limit(10);
  } catch (geoErr) {
    console.log("[DISPATCH] Geo query failed, using fallback:", geoErr.message);
    availableTeams = await Team.find({ status: "AVAILABLE" });
  }

  availableTeams = await ensureAvailableTeam({
    availableTeams,
    emergencyType,
    peopleCount,
    sosCoords,
    io,
    sosId,
    requestId,
    mode,
  });

  if (!availableTeams || availableTeams.length === 0) {
    if (io) {
      io.to("admin_room").emit("dispatch_failed", {
        sosId,
        requestId,
        mode,
        reason: "no_teams_available",
        message: `No rescue teams available for ${emergencyType} ${mode}.`,
      });
    }
    return { dispatched: false, reason: "no_teams_available" };
  }

  const nearestTeam = availableTeams
    .map((team) => ({
      team,
      distanceKm: haversineDistanceKm(team.currentLocation?.coordinates || [0, 0], sosCoords),
    }))
    .sort((a, b) => a.distanceKm - b.distanceKm)[0];

  const selectedTeam = nearestTeam.team;
  const dispatchInfo = formatDispatchInfo(selectedTeam, nearestTeam.distanceKm);

  selectedTeam.status = "DISPATCHED";
  await selectedTeam.save();

  const resetTimer = setTimeout(async () => {
    try {
      await Team.findByIdAndUpdate(selectedTeam._id, { status: "AVAILABLE" });
    } catch (_error) {
      // Ignore background reset failures.
    }
  }, 30 * 60 * 1000);
  if (typeof resetTimer.unref === "function") {
    resetTimer.unref();
  }

  emitDispatchEvents({
    io,
    mode,
    selectedTeam,
    dispatchInfo,
    userLocation,
    userId,
    sosId,
    requestId,
    emergencyType,
  });

  console.log(`[DISPATCH] Team "${selectedTeam.name}" dispatched to ${targetLabel}`);
  return dispatchInfo;
};

export async function autoDispatchService(options) {
  return dispatchNearestTeam({ ...options, mode: "sos" });
}

export async function autoAssignTeamForRequest(options) {
  return dispatchNearestTeam({ ...options, mode: "request" });
}
