import Notification from "../models/Notification.js";

/**
 * Auto-Notification Engine
 * Creates Notification record in DB + emits socket event.
 * All auto-generated notifications are marked with isAutoGenerated: true.
 *
 * @param {Object} io         - Socket.io server instance
 * @param {Object} options
 * @param {string} options.title       - Notification title
 * @param {string} options.message     - Notification body
 * @param {string} [options.type]      - 'alert' | 'broadcast' | 'warning' | 'info'
 * @param {string} [options.severity]  - 'low' | 'medium' | 'high' | 'critical'
 * @param {string} [options.userId]    - Target user ID (for personal notifications)
 * @param {string[]} [options.targetAreas] - Areas affected
 * @param {string[]} [options.rooms]   - Additional socket rooms to emit to
 */
export const emitAutoNotification = async (io, {
  title,
  message,
  type = "info",
  severity = "medium",
  userId = null,
  targetAreas = [],
  rooms = [],
}) => {
  try {
    // 1. Save to DB
    const notification = new Notification({
      title,
      message,
      type,
      severity,
      targetAreas,
      isAutoGenerated: true,
      sentBy: { name: "System (Auto)" },
      targetUserId: userId || null,
    });
    await notification.save();

    // 2. Emit socket events
    if (io) {
      const payload = {
        _id: notification._id,
        title,
        message,
        type,
        severity,
        isAutoGenerated: true,
        createdAt: notification.createdAt,
      };

      // Always notify admin room
      io.to("admin_room").emit("notification_created", payload);

      // Notify specific user if userId provided
      if (userId) {
        io.to(`user_${userId}`).emit("notification_created", payload);
        io.to(`user_${userId}`).emit("user_notification", payload);
      }

      // Notify additional rooms
      rooms.forEach((room) => {
        io.to(room).emit("notification_created", payload);
      });
    }

    return notification;
  } catch (error) {
    console.error("[AUTO-NOTIFY] Failed to create notification:", error.message);
    return null;
  }
};

/**
 * Convenience: SOS received notification (to admins)
 */
export const notifySosReceived = (io, { userName, emergencyType, sosId }) =>
  emitAutoNotification(io, {
    title: `🚨 New SOS: ${emergencyType || "Emergency"}`,
    message: `SOS received from ${userName || "Unknown user"}. Emergency type: ${emergencyType || "unknown"}.`,
    type: "alert",
    severity: "high",
    rooms: ["volunteer_room"],
  });

/**
 * Convenience: Team dispatched notification (to user)
 */
export const notifyTeamDispatched = (io, { userId, teamName, eta, memberCount }) =>
  emitAutoNotification(io, {
    title: `🚑 Rescue Team Dispatched`,
    message: `Team "${teamName}" (${memberCount} members) has been dispatched to your location. ETA: ${eta || "calculating..."}.`,
    type: "info",
    severity: "medium",
    userId,
  });

/**
 * Convenience: SOS/Request status changed (to user)
 */
export const notifyStatusChanged = (io, { userId, recordType, status, recordId }) =>
  emitAutoNotification(io, {
    title: `📋 ${recordType} Status Updated`,
    message: `Your ${recordType.toLowerCase()} has been updated to: ${status.toUpperCase()}.`,
    type: "info",
    severity: "low",
    userId,
  });

/**
 * Convenience: Request resolved — prompt review (to user)
 */
export const notifyResolvedWithReviewPrompt = (io, { userId, teamName, recordType, recordId }) =>
  emitAutoNotification(io, {
    title: `✅ ${recordType} Resolved — Rate Your Rescue Team`,
    message: `Your ${recordType.toLowerCase()} has been resolved. Team "${teamName}" helped you. Please rate their service to help improve our response.`,
    type: "info",
    severity: "low",
    userId,
  });

/**
 * Convenience: Request created notification (to admins)
 */
export const notifyRequestCreated = (io, { userName, emergencyType, description }) =>
  emitAutoNotification(io, {
    title: `📩 New Help Request: ${emergencyType || "General"}`,
    message: `Help request from ${userName || "Unknown"}: "${(description || "").slice(0, 80)}..."`,
    type: "info",
    severity: "medium",
    rooms: ["volunteer_room"],
  });

/**
 * Convenience: Team assigned to request (to user)
 */
export const notifyTeamAssigned = (io, { userId, teamName, eta, memberCount }) =>
  emitAutoNotification(io, {
    title: `🚑 Rescue Team Assigned`,
    message: `Team "${teamName}" (${memberCount} members) has been assigned to your request. ETA: ${eta || "en route"}.`,
    type: "info",
    severity: "medium",
    userId,
  });

/**
 * Emergency Broadcast — used by riskEngine.js
 * Creates a critical broadcast notification and emits to all rooms.
 */
export const triggerEmergencyBroadcast = async (io, {
  title,
  message,
  severity = "critical",
  targetAreas = [],
  location = null,
}) => {
  return emitAutoNotification(io, {
    title: `⚠️ ${title}`,
    message,
    type: "broadcast",
    severity,
    targetAreas,
    rooms: ["volunteer_room"],
  });
};
