import Request from "../models/Request.js";
import Team from "../models/Team.js";
import { autoAssignTeamForRequest } from "./autoDispatch.service.js";
import { haversineDistanceKm } from "../utils/haversine.js";

const PRIORITIES = new Set(["low", "medium", "high", "critical"]);

const toNumber = (value, fallback = 0) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};

const cleanString = (value = "") => String(value || "").trim();

const normalisePriority = (value = "") => {
  const normalized = cleanString(value).toLowerCase();
  return PRIORITIES.has(normalized) ? normalized : "medium";
};

const inferEmergencyType = (value = "") => {
  const text = cleanString(value).toLowerCase();
  if (!text) return "other";
  if (/(flood|water|drown|boat|river|paani|doob)/.test(text)) return "flood";
  if (/(fire|smoke|burn|blast|aag)/.test(text)) return "fire";
  if (/(medical|injur|ambulance|hospital|doctor|heart|breath|ghayal)/.test(text)) return "medical";
  if (/(earthquake|quake|building collapse|debris|trapped|bachao|rescue)/.test(text)) return "earthquake";
  return "other";
};

const hasUsableCoordinates = (location = {}) => {
  const lat = toNumber(location?.lat, NaN);
  const lng = toNumber(location?.lng, NaN);
  return Number.isFinite(lat) && Number.isFinite(lng) && (lat !== 0 || lng !== 0);
};

export const buildRequestDispatchSnapshot = (team, extras = {}) => ({
  teamId: team?._id || extras.teamId || null,
  teamName: team?.name || extras.teamName || "",
  memberCount: team?.memberCount || team?.memberNames?.length || extras.memberCount || 0,
  members: team?.memberNames || extras.members || [],
  memberPhones: team?.memberPhones || extras.memberPhones || [],
  leadPhone: team?.leadPhone || team?.memberPhones?.[0] || extras.leadPhone || "",
  eta: extras.eta || "",
  distance: extras.distance || "",
  status: extras.status || "EN_ROUTE",
  autoGenerated: typeof extras.autoGenerated === "boolean" ? extras.autoGenerated : Boolean(team?.autoGenerated),
  lastUpdatedAt: new Date(),
});

export const serializeRequest = (request) => {
  const item = request?.toObject ? request.toObject() : request;
  if (!item) return null;

  return {
    ...item,
    location: {
      ...item.location,
      lat: toNumber(item.location?.lat, 0),
      lng: toNumber(item.location?.lng, 0),
    },
    dispatch: item.dispatch
      ? {
          ...item.dispatch,
          members: item.dispatch.members || [],
          memberPhones: item.dispatch.memberPhones || [],
        }
      : null,
  };
};

export const populateRequestQuery = (query) =>
  query
    .populate("userId", "name phone email")
    .populate("assignedTeam", "name leadPhone memberCount memberNames memberPhones status autoGenerated");

export const buildRequestPayload = ({ body = {}, user = null }) => {
  const locationSource = body.location && typeof body.location === "object" ? body.location : {};
  const description = cleanString(body.description || body.message);

  return {
    userId: user?._id,
    name: cleanString(body.name || user?.name || "Citizen"),
    phone: cleanString(body.phone || user?.phone || ""),
    peopleCount: Math.max(1, toNumber(body.peopleCount || locationSource.peopleCount, 1)),
    description,
    priority: normalisePriority(body.priority),
    emergencyType: inferEmergencyType(body.emergencyType || body.type || description),
    status: "pending",
    location: {
      address: cleanString(locationSource.address || body.address),
      city: cleanString(locationSource.city || body.city),
      state: cleanString(locationSource.state || body.state),
      lat: toNumber(locationSource.lat ?? body.lat, 0),
      lng: toNumber(locationSource.lng ?? body.lng, 0),
    },
  };
};

export const autoAssignRequest = async (request, { io = null, userId = null } = {}) => {
  if (!hasUsableCoordinates(request.location)) {
    return { dispatched: false, reason: "missing_request_location" };
  }

  const dispatchInfo = await autoAssignTeamForRequest({
    userLocation: {
      type: "Point",
      coordinates: [toNumber(request.location.lng, 0), toNumber(request.location.lat, 0)],
      address: request.location.address || "",
    },
    emergencyType: request.emergencyType || inferEmergencyType(request.description),
    peopleCount: request.peopleCount || 1,
    requestId: request._id,
    io,
    userId,
  });

  if (dispatchInfo?.dispatched) {
    request.status = "assigned";
    request.assignedTeam = dispatchInfo.teamId;
    request.dispatch = buildRequestDispatchSnapshot(null, {
      teamId: dispatchInfo.teamId,
      teamName: dispatchInfo.team?.name,
      memberCount: dispatchInfo.team?.memberCount,
      members: dispatchInfo.team?.members,
      memberPhones: dispatchInfo.team?.memberPhones,
      leadPhone: dispatchInfo.team?.leadPhone,
      eta: dispatchInfo.eta,
      distance: dispatchInfo.distance,
      status: dispatchInfo.team?.status || "EN_ROUTE",
      autoGenerated: dispatchInfo.team?.autoGenerated,
    });
    await request.save();
  }

  return dispatchInfo;
};

export const manuallyAssignRequestTeam = async (request, team) => {
  const requestCoordinates = [toNumber(request.location?.lng, 0), toNumber(request.location?.lat, 0)];
  const teamCoordinates = team.currentLocation?.coordinates || [0, 0];
  const distanceKm = haversineDistanceKm(teamCoordinates, requestCoordinates);
  const etaMinutes = Math.max(3, Math.round((distanceKm / 40) * 60));

  request.status = "assigned";
  request.assignedTeam = team._id;
  request.dispatch = buildRequestDispatchSnapshot(team, {
    eta: etaMinutes <= 5 ? "3-5 minutes" : `${Math.max(etaMinutes - 2, 1)}-${etaMinutes + 3} minutes`,
    distance: `${distanceKm.toFixed(1)} km`,
    status: "EN_ROUTE",
  });

  team.status = "DISPATCHED";

  await Promise.all([request.save(), team.save()]);

  return request;
};

export const createAutoAssignedRequest = async ({
  payload,
  io = null,
  userId = null,
}) => {
  const request = new Request(payload);
  await request.save();

  const dispatchInfo = await autoAssignRequest(request, { io, userId });
  const hydrated = await populateRequestQuery(Request.findById(request._id));

  return {
    request: serializeRequest(hydrated),
    dispatchInfo,
  };
};

export const releaseAssignedTeamIfNeeded = async (request) => {
  if (!request?.assignedTeam) return;
  await Team.findByIdAndUpdate(request.assignedTeam, { status: "AVAILABLE" });
};
