import Alert from "../models/Alert.js";
import Timeline from "../models/Timeline.js";
import { normalizePointLocation } from "../utils/location.js";

/**
 * GET /api/alerts
 */
export const getAlerts = async (req, res) => {
  try {
    const { status, type, severity } = req.query;
    const query = {};
    if (status && status !== "all") query.status = status;
    if (type && type !== "all") query.type = type;
    if (severity && severity !== "all") query.severity = severity;

    const alerts = await Alert.find(query).sort({ createdAt: -1 });
    res.json(alerts);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * GET /api/alerts/:id
 */
export const getAlertById = async (req, res) => {
  try {
    const alert = await Alert.findById(req.params.id);
    if (!alert) return res.status(404).json({ message: "Alert not found" });
    res.json(alert);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * POST /api/alerts
 */
export const createAlert = async (req, res) => {
  try {
    const io = req.app.get("io");
    const alert = new Alert({
      ...req.body,
      location: normalizePointLocation(req.body.location, req.body.location),
      message: req.body.message || req.body.description || "",
      safetyInstructions: req.body.safetyInstructions || req.body.message || "",
      isAutoGenerated: false
    });

    await alert.save();

    // Create timeline entry
    const timeline = new Timeline({
      disasterId: alert._id,
      type: "alert",
      title: "New Alert Issued",
      description: alert.title,
      timestamp: alert.createdAt
    });
    await timeline.save();

    if (io) {
      io.emit("new_alert", alert);
    }

    res.status(201).json(alert);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * PATCH /api/alerts/:id
 */
export const updateAlert = async (req, res) => {
  try {
    const updatePayload = { ...req.body };
    if (req.body.location) {
      updatePayload.location = normalizePointLocation(req.body.location, req.body.location);
    }
    const alert = await Alert.findByIdAndUpdate(
      req.params.id,
      updatePayload,
      { new: true }
    );
    if (!alert) return res.status(404).json({ message: "Alert not found" });
    res.json(alert);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * DELETE /api/alerts/:id
 */
export const deleteAlert = async (req, res) => {
  try {
    const alert = await Alert.findByIdAndDelete(req.params.id);
    if (!alert) return res.status(404).json({ message: "Alert not found" });
    res.json({ message: "Alert deleted" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * GET /api/timeline/:id
 */
export const getTimeline = async (req, res) => {
  try {
    const timeline = await Timeline.find({ disasterId: req.params.id }).sort({ timestamp: -1 });
    res.json(timeline);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * POST /api/timeline
 */
export const createTimelineEntry = async (req, res) => {
  try {
    const { disasterId, type, title, description } = req.body;

    if (!disasterId || !title) {
      return res.status(400).json({ message: "disasterId and title are required" });
    }

    const timeline = new Timeline({
      disasterId,
      type: type || "manual",
      title,
      description: description || "",
      timestamp: new Date()
    });

    await timeline.save();
    res.status(201).json(timeline);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
