import Team from "../models/Team.js";

/**
 * GET /api/teams
 */
export const getTeams = async (req, res) => {
  try {
    const { status, specialization, search } = req.query;
    const query = {};

    if (status && status !== "all") query.status = status;
    if (specialization && specialization !== "all") query.specialization = specialization;
    if (search) {
      query.$or = [
        { name: { $regex: search, $options: "i" } },
        { memberNames: { $regex: search, $options: "i" } },
        { leadPhone: { $regex: search, $options: "i" } },
      ];
    }

    const teams = await Team.find(query).sort({ createdAt: -1 });
    res.json(teams);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * GET /api/teams/:id
 */
export const getTeamById = async (req, res) => {
  try {
    const team = await Team.findById(req.params.id);
    if (!team) return res.status(404).json({ message: "Team not found" });
    res.json(team);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * POST /api/teams
 */
export const createTeam = async (req, res) => {
  try {
    const {
      name, capacity, status, specialization,
      memberNames, memberPhones, leadName, leadPhone,
      currentLocation
    } = req.body;

    const team = new Team({
      name,
      capacity,
      status: String(status || "AVAILABLE").toUpperCase(),
      specialization: specialization || "general",
      memberNames: memberNames || [],
      memberPhones: memberPhones || [],
      leadName: leadName || "",
      leadPhone: leadPhone || "",
      currentLocation,
      autoGenerated: false, // Admin-created teams are never auto-generated
    });

    await team.save();
    res.status(201).json(team);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * PUT /api/teams/:id
 *
 * BUG FIX: Previously used findByIdAndUpdate which SKIPS Mongoose pre('validate')
 * hooks. Now uses findById() + manual field assignment + save() so all hooks run.
 */
export const updateTeam = async (req, res) => {
  try {
    const team = await Team.findById(req.params.id);
    if (!team) return res.status(404).json({ message: "Team not found" });

    const {
      name, capacity, status, specialization,
      memberNames, memberPhones, leadName, leadPhone,
      currentLocation
    } = req.body;

    // Apply updates — only override what's provided
    if (name !== undefined) team.name = name;
    if (capacity !== undefined) team.capacity = Number(capacity);
    if (status !== undefined) team.status = String(status).toUpperCase();
    if (specialization !== undefined) team.specialization = specialization;

    // Member data — replace entirely if provided
    if (Array.isArray(memberNames)) team.memberNames = memberNames;
    if (Array.isArray(memberPhones)) team.memberPhones = memberPhones;
    if (leadName !== undefined) team.leadName = leadName;
    if (leadPhone !== undefined) team.leadPhone = leadPhone;

    // Location
    if (currentLocation?.coordinates) {
      team.currentLocation = currentLocation;
    }

    // If admin provides real member data, mark as non-auto-generated
    if (Array.isArray(memberNames) && memberNames.length > 0) {
      team.autoGenerated = false;
    }

    await team.save(); // This triggers pre('validate') hooks!
    res.json(team);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * DELETE /api/teams/:id
 */
export const deleteTeam = async (req, res) => {
  try {
    const team = await Team.findByIdAndDelete(req.params.id);
    if (!team) return res.status(404).json({ message: "Team not found" });
    res.json({ message: "Team deleted" });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

/**
 * PATCH /api/teams/bulk-status
 * Body: { teamIds: [id1, id2, ...], status: "AVAILABLE" | "DISPATCHED" | "INACTIVE" }
 */
export const bulkUpdateStatus = async (req, res) => {
  try {
    const { teamIds, status } = req.body;

    const result = await Team.updateMany(
      { _id: { $in: teamIds } },
      { $set: { status: String(status).toUpperCase() } }
    );

    res.json({
      message: `${result.modifiedCount} team(s) updated to ${status}`,
      modifiedCount: result.modifiedCount,
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
