import { useState } from "react";
import PublicLayout from "../../modules/public/PublicLayout.jsx";
import api from "../../api/axios.js";

const PRIORITIES = ["low", "medium", "high", "critical"];

const toDispatchCard = (dispatch = {}) => ({
  teamId: dispatch.teamId || dispatch.id || "",
  teamName: dispatch.teamName || dispatch.name || "Assigned Rescue Team",
  memberCount: dispatch.memberCount || dispatch.members?.length || 0,
  members: dispatch.members || [],
  memberPhones: dispatch.memberPhones || [],
  leadPhone: dispatch.leadPhone || dispatch.memberPhones?.[0] || "",
  eta: dispatch.eta || "10-15 minutes",
  distance: dispatch.distance || "",
  status: dispatch.status || "EN_ROUTE",
  autoGenerated: Boolean(dispatch.autoGenerated),
});

const PublicRequestHelp = () => {
  const [form, setForm] = useState({
    name: "",
    phone: "",
    peopleCount: "",
    description: "",
    priority: "medium",
    address: "",
    city: "",
    state: "",
    lat: "",
    lng: "",
  });
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [locating, setLocating] = useState(false);
  const [submittedRequest, setSubmittedRequest] = useState(null);
  const [assignedTeam, setAssignedTeam] = useState(null);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm((current) => ({ ...current, [name]: value }));
  };

  const getLocation = () => {
    setLocating(true);
    navigator.geolocation.getCurrentPosition(
      (position) => {
        setForm((current) => ({
          ...current,
          lat: position.coords.latitude.toFixed(6),
          lng: position.coords.longitude.toFixed(6),
        }));
        setLocating(false);
      },
      (geoError) => {
        setError(`Location access denied: ${geoError.message}`);
        setLocating(false);
      }
    );
  };

  const resetForm = () => {
    setForm({
      name: "",
      phone: "",
      peopleCount: "",
      description: "",
      priority: "medium",
      address: "",
      city: "",
      state: "",
      lat: "",
      lng: "",
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");
    setMessage("");
    setLoading(true);
    setAssignedTeam(null);

    try {
      const { data } = await api.post("/public/help-request", {
        name: form.name,
        phone: form.phone,
        peopleCount: Number(form.peopleCount) || 1,
        priority: form.priority,
        description: form.description,
        location: {
          lat: Number(form.lat),
          lng: Number(form.lng),
          address: form.address,
          city: form.city,
          state: form.state,
        },
      });

      setMessage(data?.message || "Request submitted successfully.");
      setSubmittedRequest(data?.request || null);
      setAssignedTeam(
        data?.assignedTeam
          ? toDispatchCard({
              ...data.assignedTeam,
              teamId: data.assignedTeam.id,
              teamName: data.assignedTeam.name,
            })
          : data?.request?.dispatch
            ? toDispatchCard(data.request.dispatch)
            : null
      );
      resetForm();
    } catch (err) {
      setError(err?.response?.data?.message || err.message || "Failed to submit request. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <PublicLayout>
      <div style={{ maxWidth: 720 }}>
        <div style={{ marginBottom: 24 }}>
          <h1 style={{ fontSize: 26, fontWeight: 800 }}>Emergency Help Request</h1>
          <p style={{ color: "var(--text-2)", marginTop: 6 }}>
            Share your situation and location. If a team is available, it will be assigned automatically and you will see direct contact numbers here.
          </p>
        </div>

        {message && <div className="alert alert-success">{message}</div>}
        {error && <div className="alert alert-error">{error}</div>}

        {submittedRequest && (
          <div className="card" style={{ marginBottom: 20 }}>
            <div className="card-header">
              <span className="card-title">Latest Help Request</span>
              <span className="badge badge-primary">{submittedRequest.status || "pending"}</span>
            </div>
            <div style={{ display: "grid", gap: 8, fontSize: 13 }}>
              <div><strong>Request ID:</strong> {submittedRequest._id}</div>
              <div><strong>Priority:</strong> {submittedRequest.priority}</div>
              <div><strong>People Affected:</strong> {submittedRequest.peopleCount || 1}</div>
              <div><strong>Location:</strong> {submittedRequest.location?.address || `${submittedRequest.location?.city || ""} ${submittedRequest.location?.state || ""}`.trim() || "GPS shared"}</div>
            </div>
          </div>
        )}

        {assignedTeam && (
          <div className="card" style={{ marginBottom: 24, border: "1px solid rgba(59,130,246,0.24)" }}>
            <div className="card-header">
              <span className="card-title">Assigned Rescue Team</span>
              <span className="badge badge-success">{assignedTeam.status}</span>
            </div>

            <div style={{ display: "grid", gap: 12 }}>
              <div style={{ display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 10 }}>
                <div className="card" style={{ background: "var(--panel-2)" }}>
                  <div className="muted" style={{ fontSize: 11 }}>Team</div>
                  <div style={{ fontWeight: 700 }}>{assignedTeam.teamName}</div>
                </div>
                <div className="card" style={{ background: "var(--panel-2)" }}>
                  <div className="muted" style={{ fontSize: 11 }}>ETA</div>
                  <div style={{ fontWeight: 700 }}>{assignedTeam.eta}</div>
                </div>
                <div className="card" style={{ background: "var(--panel-2)" }}>
                  <div className="muted" style={{ fontSize: 11 }}>Distance</div>
                  <div style={{ fontWeight: 700 }}>{assignedTeam.distance || "Calculating..."}</div>
                </div>
              </div>

              {assignedTeam.leadPhone && (
                <a
                  href={`tel:${assignedTeam.leadPhone.replace(/[^+\d]/g, "")}`}
                  className="btn btn-success"
                  style={{ width: "fit-content" }}
                >
                  Call Team Lead: {assignedTeam.leadPhone}
                </a>
              )}

              <div style={{ display: "grid", gap: 8 }}>
                {(assignedTeam.members || []).map((member, index) => {
                  const phone = assignedTeam.memberPhones?.[index];
                  return (
                    <div
                      key={`${member}-${index}`}
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                        background: "var(--panel-2)",
                        borderRadius: 10,
                        padding: "10px 12px",
                      }}
                    >
                      <div>
                        <div style={{ fontWeight: 600 }}>{member}</div>
                        <div className="muted" style={{ fontSize: 11 }}>
                          {index === 0 ? "Team Lead" : "Rescue Member"}
                        </div>
                      </div>
                      {phone ? (
                        <a href={`tel:${phone.replace(/[^+\d]/g, "")}`} className="btn btn-sm">
                          {phone}
                        </a>
                      ) : (
                        <span className="muted">Phone unavailable</span>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        )}

        <form onSubmit={handleSubmit}>
          <div className="form-section">
            <div className="form-section-title">Your Information</div>
            <div className="grid grid-2">
              <div className="form-group">
                <label className="form-label">Full Name *</label>
                <input
                  className="input"
                  name="name"
                  value={form.name}
                  onChange={handleChange}
                  placeholder="Your full name"
                  required
                />
              </div>
              <div className="form-group">
                <label className="form-label">Phone Number *</label>
                <input
                  className="input"
                  name="phone"
                  value={form.phone}
                  onChange={handleChange}
                  placeholder="+91 98765 43210"
                  required
                />
              </div>
            </div>

            <div className="grid grid-2">
              <div className="form-group">
                <label className="form-label">Number of People Affected</label>
                <input
                  className="input"
                  name="peopleCount"
                  type="number"
                  min="1"
                  value={form.peopleCount}
                  onChange={handleChange}
                  placeholder="e.g. 5"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Priority Level</label>
                <select className="select" name="priority" value={form.priority} onChange={handleChange}>
                  {PRIORITIES.map((priority) => (
                    <option key={priority} value={priority}>
                      {priority.charAt(0).toUpperCase() + priority.slice(1)}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">Describe the Emergency *</label>
              <textarea
                className="textarea"
                name="description"
                value={form.description}
                onChange={handleChange}
                placeholder="Briefly describe the situation, injuries, and what help is needed..."
                required
              />
            </div>
          </div>

          <div className="form-section">
            <div className="form-section-title">Your Location</div>
            <div className="grid grid-2">
              <div className="form-group">
                <label className="form-label">Street Address</label>
                <input
                  className="input"
                  name="address"
                  value={form.address}
                  onChange={handleChange}
                  placeholder="Street address"
                />
              </div>
              <div className="form-group">
                <label className="form-label">City</label>
                <input className="input" name="city" value={form.city} onChange={handleChange} placeholder="City" />
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">State</label>
              <input className="input" name="state" value={form.state} onChange={handleChange} placeholder="State" />
            </div>

            <div className="grid grid-2">
              <div className="form-group">
                <label className="form-label">Latitude (GPS)</label>
                <input
                  className="input"
                  name="lat"
                  type="number"
                  step="any"
                  value={form.lat}
                  onChange={handleChange}
                  placeholder="e.g. 28.6139"
                />
              </div>
              <div className="form-group">
                <label className="form-label">Longitude (GPS)</label>
                <input
                  className="input"
                  name="lng"
                  type="number"
                  step="any"
                  value={form.lng}
                  onChange={handleChange}
                  placeholder="e.g. 77.2090"
                />
              </div>
            </div>

            <button type="button" className="btn" onClick={getLocation} disabled={locating}>
              {locating ? "Detecting..." : "Auto-Detect My Location"}
            </button>
          </div>

          <button className="btn btn-danger btn-lg" type="submit" disabled={loading}>
            {loading ? "Submitting..." : "Submit Emergency Request"}
          </button>
        </form>

        <div
          className="card"
          style={{
            marginTop: 24,
            background: "rgba(239,68,68,0.05)",
            border: "1px solid rgba(239,68,68,0.2)",
            textAlign: "center",
          }}
        >
          <p style={{ fontSize: 13, color: "var(--text-2)" }}>
            If you are in immediate danger, call <strong style={{ color: "var(--danger)", fontSize: 16 }}>112</strong> immediately.
          </p>
        </div>
      </div>
    </PublicLayout>
  );
};

export default PublicRequestHelp;
