import { useState, useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import PublicLayout from "../../modules/public/PublicLayout.jsx";
import { useAuth } from "../../context/AuthContext.jsx";
import LeafletMap from "../../components/LeafletMap.jsx";
import api from "../../api/axios.js";
import { socket } from "../../socket/socket.js";
import ReviewForm from "../../components/ReviewForm.jsx";

const EMERGENCY_TYPES = [
  { key: "flood", icon: "🌊", label: "Flood" },
  { key: "fire", icon: "🔥", label: "Fire" },
  { key: "earthquake", icon: "🏚️", label: "Earthquake" },
  { key: "medical", icon: "🏥", label: "Medical" },
  { key: "trapped", icon: "🧱", label: "Trapped" },
  { key: "other", icon: "⚠️", label: "Other" },
];

const toDispatchCard = (dispatch = {}) => ({
  teamId: dispatch.teamId || dispatch.id || "",
  teamName: dispatch.teamName || dispatch.name || "Assigned Rescue Team",
  memberCount: dispatch.memberCount || dispatch.members?.length || 0,
  members: dispatch.members || [],
  memberPhones: dispatch.memberPhones || [],
  leadPhone: dispatch.leadPhone || dispatch.memberPhones?.[0] || "",
  eta: dispatch.eta || "10-15 minutes",
  distance: dispatch.distance || "",
  status: dispatch.status || "EN_ROUTE",
  autoGenerated: Boolean(dispatch.autoGenerated),
});

const SOSPage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [location, setLocation] = useState(null);
  const [locError, setLocError] = useState("");
  const [message, setMessage] = useState("");
  const [image, setImage] = useState(null);
  const [video, setVideo] = useState(null);
  const [previews, setPreviews] = useState({ image: null, video: null });
  const [sending, setSending] = useState(false);
  const [success, setSuccess] = useState(null);
  const [aiResponse, setAiResponse] = useState("");
  const [dispatchedTeam, setDispatchedTeam] = useState(null);
  const [spamWarning, setSpamWarning] = useState(null);

  const [history, setHistory] = useState([]);
  const [emergencyType, setEmergencyType] = useState("");
  const [peopleCount, setPeopleCount] = useState(1);
  const [countdown, setCountdown] = useState(null);
  const [isOffline, setIsOffline] = useState(!navigator.onLine);
  const [reviewedSosIds, setReviewedSosIds] = useState(new Set());
  const countdownRef = useRef(null);

  // Online/offline detection
  useEffect(() => {
    const goOnline = () => setIsOffline(false);
    const goOffline = () => setIsOffline(true);
    window.addEventListener("online", goOnline);
    window.addEventListener("offline", goOffline);
    return () => {
      window.removeEventListener("online", goOnline);
      window.removeEventListener("offline", goOffline);
    };
  }, []);

  // GPS
  useEffect(() => {
    if (!navigator.geolocation) {
      setLocError("Geolocation not supported by your browser.");
      return;
    }
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        setLocation({ lat: pos.coords.latitude, lng: pos.coords.longitude });
        setLocError("");
      },
      () => setLocError("Could not access GPS. Please enable location access.")
    );
  }, []);

  // SOS history
  useEffect(() => {
    if (user) {
      api.get("/sos/mine")
        .then((r) => {
          const items = r.data || [];
          setHistory(items);

          const latestActiveSOS = items.find((item) =>
            ["active", "acknowledged", "dispatched"].includes(item.status)
          );

          if (latestActiveSOS?.dispatch?.teamName) {
            setSuccess("Active SOS in progress");
            setDispatchedTeam(toDispatchCard(latestActiveSOS.dispatch));
          }
        })
        .catch(() => {});
    }
  }, [user]);

  // Countdown timer after SOS sent
  useEffect(() => {
    if (countdown !== null && countdown > 0) {
      countdownRef.current = setTimeout(() => setCountdown((c) => c - 1), 1000);
    }
    return () => clearTimeout(countdownRef.current);
  }, [countdown]);

  if (!user) {
    return (
      <PublicLayout>
        <div className="card" style={{ maxWidth: 480, margin: "60px auto", textAlign: "center" }}>
          <div style={{ fontSize: 48, marginBottom: 16 }}>🔐</div>
          <h2>Login Required for SOS</h2>
          <p className="muted" style={{ margin: "12px 0 20px" }}>
            SOS requires a verified account so rescue teams know who to help.
          </p>
          <button className="btn btn-primary" onClick={() => navigate("/login")}>Sign In</button>
        </div>
      </PublicLayout>
    );
  }

  const handleImage = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImage(file);
      setPreviews((p) => ({ ...p, image: URL.createObjectURL(file) }));
    }
  };

  const handleVideo = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (file.size > 50 * 1024 * 1024) return alert("Video too large (max 50MB)");
      setVideo(file);
      setPreviews((p) => ({ ...p, video: URL.createObjectURL(file) }));
    }
  };
  // Socket listener for real-time updates
  useEffect(() => {
    if (!socket) return;

    const handleAutoReply = (data) => {
      console.log("[SOCKET] Auto-reply received:", data);
      setAiResponse(data.message);
      setSuccess("SOS Processed");
      setCountdown(15 * 60);
    };

    const handleTeamDispatch = (data) => {
      console.log("[SOCKET] Team dispatched:", data);
      setDispatchedTeam(toDispatchCard(data));
    };

    socket.on('auto_reply', handleAutoReply);
    socket.on('guest_auto_reply', handleAutoReply);
    socket.on('sos_dispatched', handleTeamDispatch);
    socket.on('team_dispatched', handleTeamDispatch);
    socket.on('sos_status_updated', () => {
      if (user) api.get("/sos/mine").then((r) => setHistory(r.data || [])).catch(() => {});
    });

    return () => {
      socket.off('auto_reply', handleAutoReply);
      socket.off('guest_auto_reply', handleAutoReply);
      socket.off('sos_dispatched', handleTeamDispatch);
      socket.off('team_dispatched', handleTeamDispatch);
      socket.off('sos_status_updated');
    };
  }, []);


  const sendSOS = async () => {
    if (!location) {
      alert("Cannot send SOS without GPS location. Please enable location access.");
      return;
    }
    setSending(true);
    setSpamWarning(null);
    setDispatchedTeam(null);

    try {
      const formData = new FormData();
      formData.append("lat", location.lat);
      formData.append("lng", location.lng);
      formData.append("address", `Lat: ${location.lat.toFixed(4)}, Lng: ${location.lng.toFixed(4)}`);
      
      const fullMsg = [
        message || "SOS Emergency!",
        emergencyType ? `Type: ${emergencyType}` : "",
        peopleCount > 1 ? `People: ${peopleCount}` : "",
      ].filter(Boolean).join(" | ");
      
      formData.append("message", fullMsg);
      formData.append("peopleCount", peopleCount);
      if (image) formData.append("image", image);
      if (video) formData.append("video", video);

      const { data } = await api.post("/sos", formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });

      console.log("[SOS] API Response:", JSON.stringify(data, null, 2));

      // Check if SOS was flagged as spam
      if (data.sos?.status === 'spam') {
        setSpamWarning({
          message: data.message,
          reason: "Message flagged by AI system as low-confidence or potentially false.",
          score: data.sos.spamScore,
        });
        setSuccess(null);
      } else {
        setSuccess(data.message);
        setAiResponse(data.aiResponse || "");
        setCountdown(15 * 60);
        
        // ★ Read dispatched team from HTTP response (new format)
        if (data.dispatchedTeam) {
          setDispatchedTeam(
            toDispatchCard({
              ...data.dispatchedTeam,
              teamId: data.dispatchedTeam.id,
              teamName: data.dispatchedTeam.name,
              eta: data.estimatedArrival,
              distance: data.distance,
            })
          );

        }
      }

      const hist = await api.get("/sos/mine");
      setHistory(hist.data || []);

      setImage(null);
      setVideo(null);
      setPreviews({ image: null, video: null });
    } catch (err) {
      const errMsg = err?.response?.data?.message || err.message || "Failed to send SOS";
      alert(errMsg);
    } finally {
      setSending(false);
    }
  };



  const formatCountdown = (secs) => {
    if (!secs || secs <= 0) return "00:00";
    const m = Math.floor(secs / 60);
    const s = secs % 60;
    return `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  };

  const statusColor = {
    active: "var(--danger)",
    acknowledged: "var(--warning)",
    dispatched: "var(--primary)",
    resolved: "var(--success)",
    spam: "#6b7280",
  };

  const statusStep = { active: 0, acknowledged: 1, dispatched: 2, resolved: 3, spam: -1 };
  const statusLabels = ["🆘 SOS Sent", "👁 Acknowledged", "🚑 Team Dispatched", "✅ Resolved"];

  return (
    <PublicLayout>
      <div style={{ maxWidth: 640, margin: "0 auto" }}>
        {/* Offline notice */}
        {isOffline && (
          <div className="offline-notice">
            <span style={{ fontSize: 18 }}>📡</span>
            <div>
              <strong>You are offline</strong>
              <div style={{ fontSize: 11, color: "var(--text-2)" }}>SOS will be sent as soon as connectivity is restored.</div>
            </div>
          </div>
        )}

        <div style={{ textAlign: "center", marginBottom: 32 }}>
          <h1 style={{ fontSize: 28, fontWeight: 800 }}>🆘 Emergency SOS</h1>
          <p style={{ color: "var(--text-2)", marginTop: 8, fontSize: 15 }}>
            Press the SOS button to instantly alert rescue teams with your current GPS location.
          </p>
        </div>

        {/* Live Location Map */}
        <div className="card" style={{ marginBottom: 20, padding: 0, overflow: "hidden" }}>
          <div style={{
            padding: "12px 16px", borderBottom: "1px solid var(--border)",
            display: "flex", justifyContent: "space-between", alignItems: "center"
          }}>
            <span style={{ fontWeight: 600, fontSize: 14 }}>📍 Your Live Location</span>
            {location ? (
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <div className="pulse-dot" />
                <span style={{ fontSize: 12, color: "var(--success)" }}>
                  {location.lat.toFixed(5)}, {location.lng.toFixed(5)}
                </span>
              </div>
            ) : (
              <span style={{ fontSize: 12, color: "var(--warning)" }}>Detecting...</span>
            )}
          </div>
          {locError ? (
            <div className="alert alert-error" style={{ margin: 16 }}>⚠ {locError}</div>
          ) : (
            <LeafletMap
              height={280}
              center={location ? [location.lat, location.lng] : [22.5, 78.5]}
              zoom={location ? 15 : 5}
              userLocation={location}
              className=""
            />
          )}
        </div>

        {/* Spam Warning Banner */}
        {spamWarning && (
          <div className="card" style={{
            textAlign: "center",
            background: "linear-gradient(135deg, rgba(245,158,11,0.08), rgba(239,68,68,0.08))",
            border: "2px solid var(--warning)",
            marginBottom: 20,
          }}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>🛡️</div>
            <h2 style={{ color: "var(--warning)", marginBottom: 8 }}>SOS Flagged for Review</h2>
            <p style={{ color: "var(--text-2)", marginBottom: 12, fontSize: 14 }}>
              {spamWarning.message}
            </p>
            <div style={{
              background: "rgba(245,158,11,0.1)", borderRadius: 8, padding: "12px 16px",
              marginBottom: 16, textAlign: "left", fontSize: 12
            }}>
              <div style={{ fontWeight: 700, marginBottom: 6, color: "var(--warning)" }}>🔍 Detection Reason:</div>
              <div style={{ color: "var(--text-2)" }}>{spamWarning.reason}</div>
              <div style={{ marginTop: 8, color: "var(--muted)" }}>Spam Score: {spamWarning.score}/100</div>
            </div>
            <div style={{
              background: "rgba(239,68,68,0.08)", borderRadius: 8, padding: "14px",
              border: "1px solid rgba(239,68,68,0.2)", marginBottom: 16
            }}>
              <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 6 }}>🚨 Is this a real emergency?</div>
              <p style={{ fontSize: 13, color: "var(--text-2)", margin: 0 }}>
                If you are in genuine danger, please call <a href="tel:112" style={{ color: "var(--danger)", fontWeight: 800, fontSize: 16 }}>📞 112</a> immediately.
                An admin will also review your SOS and can manually dispatch a team.
              </p>
            </div>
            <button className="btn btn-warning" onClick={() => setSpamWarning(null)} style={{ marginRight: 8 }}>
              Try Again
            </button>
            <a href="tel:112" className="btn btn-danger">Call 112 Now</a>
          </div>
        )}

        {/* SOS Panel */}
        {success ? (
          <div className="card" style={{ textAlign: "center", background: "rgba(16,185,129,0.05)", border: "1px solid rgba(16,185,129,0.3)" }}>
            <div style={{ fontSize: 48, marginBottom: 12 }}>✅</div>
            <h2 style={{ color: "var(--success)", marginBottom: 8 }}>SOS Sent!</h2>
            {aiResponse ? (
              <div style={{ 
                background: "rgba(16,185,129,0.1)", 
                borderRadius: 12, 
                padding: "16px 20px", 
                marginBottom: 20,
                border: "1px dashed var(--success)",
                textAlign: "left",
                position: "relative"
              }}>
                <div style={{ fontSize: 12, fontWeight: 800, textTransform: "uppercase", marginBottom: 8, color: "var(--success)", display: "flex", alignItems: "center", gap: 6 }}>
                  <span>🤖 AI Response Engine:</span>
                </div>
                <p style={{ color: "var(--text-1)", margin: 0, fontSize: 15, fontWeight: 500, lineHeight: 1.5 }}>
                  {aiResponse}
                </p>
              </div>
            ) : (
              <p style={{ color: "var(--text-2)", marginBottom: 16 }}>
                Rescue teams have been alerted with your exact GPS coordinates. Please stay calm and remain in a safe location.
              </p>
            )}

            {/* Dispatched Team Details */}
            {dispatchedTeam && (
              <div className="card" style={{ 
                background: "linear-gradient(135deg, rgba(59,130,246,0.08), rgba(16,185,129,0.05))", 
                border: "1px solid rgba(59,130,246,0.3)", 
                textAlign: "left", 
                marginBottom: 20 
              }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
                  <div style={{ fontSize: 28, animation: "sosPulse 2s infinite" }}>🚐</div>
                  <div style={{ flex: 1 }}>
                    <h4 style={{ margin: 0, color: "var(--primary)", fontSize: 16 }}>Rescue Team Dispatched!</h4>
                    <div style={{ fontSize: 12, color: "var(--muted)" }}>Live tracking active — team en route to your coordinates</div>
                  </div>
                  <span className="badge" style={{ background: "rgba(16,185,129,0.15)", color: "var(--success)", fontSize: 11, fontWeight: 700, padding: "4px 10px" }}>
                    {dispatchedTeam.status || "EN_ROUTE"}
                  </span>
                </div>
                
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12, fontSize: 13, marginBottom: 14 }}>
                  <div style={{ background: "rgba(59,130,246,0.06)", borderRadius: 8, padding: "10px 12px" }}>
                    <div style={{ color: "var(--muted)", fontSize: 10, textTransform: "uppercase", fontWeight: 700 }}>Team Name</div>
                    <div style={{ fontWeight: 700, marginTop: 4 }}>{dispatchedTeam.teamName}</div>
                  </div>
                  <div style={{ background: "rgba(16,185,129,0.06)", borderRadius: 8, padding: "10px 12px" }}>
                    <div style={{ color: "var(--muted)", fontSize: 10, textTransform: "uppercase", fontWeight: 700 }}>ETA</div>
                    <div style={{ fontWeight: 700, color: "var(--primary)", marginTop: 4 }}>{dispatchedTeam.eta}</div>
                  </div>
                  <div style={{ background: "rgba(245,158,11,0.06)", borderRadius: 8, padding: "10px 12px" }}>
                    <div style={{ color: "var(--muted)", fontSize: 10, textTransform: "uppercase", fontWeight: 700 }}>Distance</div>
                    <div style={{ fontWeight: 700, color: "var(--warning)", marginTop: 4 }}>{dispatchedTeam.distance || "Calculating..."}</div>
                  </div>
                </div>

                {/* Team Leader Quick Call */}
                {dispatchedTeam.leadPhone && (
                  <a href={`tel:${dispatchedTeam.leadPhone.replace(/[^+\d]/g, '')}`}
                    style={{
                      display: "flex", alignItems: "center", gap: 10,
                      background: "linear-gradient(135deg, rgba(16,185,129,0.12), rgba(59,130,246,0.08))",
                      borderRadius: 10, padding: "12px 16px", marginBottom: 14,
                      border: "1px solid rgba(16,185,129,0.3)",
                      textDecoration: "none", color: "inherit", cursor: "pointer",
                      transition: "transform 0.15s ease"
                    }}
                    onMouseEnter={e => e.currentTarget.style.transform = "scale(1.02)"}
                    onMouseLeave={e => e.currentTarget.style.transform = "scale(1)"}
                  >
                    <div style={{ fontSize: 28 }}>📞</div>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 13, fontWeight: 800, color: "var(--success)" }}>Call Team Leader Directly</div>
                      <div style={{ fontSize: 12, color: "var(--muted)", marginTop: 2 }}>
                        {dispatchedTeam.members?.[0] || "Team Leader"} — Describe the environment & situation
                      </div>
                    </div>
                    <div style={{ fontSize: 16, fontWeight: 800, color: "var(--success)", whiteSpace: "nowrap" }}>
                      {dispatchedTeam.leadPhone}
                    </div>
                  </a>
                )}

                {/* All Team Members with Phone */}
                <div style={{ background: "rgba(59,130,246,0.04)", borderRadius: 8, padding: "10px 14px", border: "1px dashed rgba(59,130,246,0.15)" }}>
                  <div style={{ color: "var(--muted)", fontSize: 10, textTransform: "uppercase", fontWeight: 700, marginBottom: 8 }}>
                    👥 Team Members ({dispatchedTeam.memberCount || 0}) — Tap to call
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                    {dispatchedTeam.members && dispatchedTeam.members.length > 0 
                      ? dispatchedTeam.members.map((name, i) => {
                          const phone = dispatchedTeam.memberPhones?.[i] || "";
                          return (
                            <div key={i} style={{
                              display: "flex", alignItems: "center", justifyContent: "space-between",
                              background: "rgba(59,130,246,0.06)", borderRadius: 8, padding: "8px 12px"
                            }}>
                              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                                <span style={{ 
                                  width: 28, height: 28, borderRadius: "50%", 
                                  background: "rgba(59,130,246,0.15)", display: "flex", 
                                  alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700,
                                  color: "var(--primary)"
                                }}>{name.charAt(0)}</span>
                                <div>
                                  <div style={{ fontSize: 13, fontWeight: 600 }}>{name}</div>
                                  {i === 0 && <span style={{ fontSize: 9, color: "var(--success)", fontWeight: 700, textTransform: "uppercase" }}>Team Leader</span>}
                                </div>
                              </div>
                              {phone ? (
                                <a href={`tel:${phone.replace(/[^+\d]/g, '')}`}
                                  style={{
                                    display: "flex", alignItems: "center", gap: 4,
                                    background: "rgba(16,185,129,0.12)", color: "var(--success)",
                                    borderRadius: 6, padding: "4px 10px", fontSize: 12, fontWeight: 600,
                                    textDecoration: "none", border: "1px solid rgba(16,185,129,0.2)"
                                  }}
                                >
                                  📱 {phone}
                                </a>
                              ) : (
                                <span style={{ fontSize: 11, color: "var(--muted)" }}>No phone</span>
                              )}
                            </div>
                          );
                        })
                      : <span style={{ color: "var(--muted)" }}>Advanced Response Unit</span>
                    }
                  </div>
                </div>
              </div>
            )}



            {/* Countdown Timer */}
            {countdown !== null && countdown > 0 && (
              <div className="sos-countdown">
                <div>
                  <div className="sos-countdown-timer">{formatCountdown(countdown)}</div>
                </div>
                <div className="sos-countdown-label">
                  <strong>Estimated Response Time</strong><br />
                  A rescue team is being dispatched to your location
                </div>
              </div>
            )}

            {/* Status Pipeline */}
            <div style={{ margin: "20px 0", padding: "0 16px" }}>
              <div style={{ display: "flex", justifyContent: "space-between", gap: 4 }}>
                {statusLabels.map((label, i) => {
                  const activeStep = dispatchedTeam ? 2 : 0; // Step 2 = dispatched
                  const isActive = i <= activeStep;
                  return (
                    <div key={i} style={{ flex: 1, textAlign: "center" }}>
                      <div style={{
                        width: "100%", height: 4, borderRadius: 2, marginBottom: 6,
                        background: isActive ? "var(--success)" : "var(--border)",
                        transition: "background 0.5s ease"
                      }} />
                      <span style={{ fontSize: 10, color: isActive ? "var(--success)" : "var(--muted)", fontWeight: 600 }}>
                        {label}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>

            <button className="btn btn-danger" onClick={() => { setSuccess(null); setCountdown(null); setDispatchedTeam(null); }}>
              Send Another SOS
            </button>
          </div>

        ) : (
          <div className="sos-panel">
            <h3 style={{ fontWeight: 700, marginBottom: 6 }}>Press to Send Emergency Alert</h3>
            <p style={{ color: "var(--text-2)", fontSize: 13, marginBottom: 16 }}>
              We'll share your exact GPS coordinates and details with the nearest rescue team in real-time.
            </p>

            {/* Emergency Type Selector */}
            <div style={{ marginBottom: 16 }}>
              <label className="form-label" style={{ textAlign: "left" }}>Type of Emergency</label>
              <div className="sos-type-grid">
                {EMERGENCY_TYPES.map((t) => (
                  <button
                    key={t.key}
                    className={`sos-type-btn ${emergencyType === t.key ? "selected" : ""}`}
                    onClick={() => setEmergencyType(t.key === emergencyType ? "" : t.key)}
                    type="button"
                  >
                    <span className="sos-type-icon">{t.icon}</span>
                    {t.label}
                  </button>
                ))}
              </div>
            </div>

            {/* People Count */}
            <div className="form-group" style={{ textAlign: "left" }}>
              <label className="form-label">People Needing Help</label>
              <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <button className="btn btn-sm" onClick={() => setPeopleCount(Math.max(1, peopleCount - 1))} type="button">−</button>
                <span style={{ fontSize: 24, fontWeight: 800, minWidth: 40, textAlign: "center" }}>{peopleCount}</span>
                <button className="btn btn-sm" onClick={() => setPeopleCount(peopleCount + 1)} type="button">+</button>
                <span style={{ fontSize: 12, color: "var(--muted)" }}>person{peopleCount > 1 ? "s" : ""}</span>
              </div>
            </div>

            {/* SOS Button */}
            <div className="sos-btn-wrap">
              <div className="sos-rings" />
              <div className="sos-rings" />
              <div className="sos-rings" />
              <button
                className="sos-main-btn"
                onClick={sendSOS}
                disabled={sending || !location}
                id="sos-trigger-button"
              >
                <span>{sending ? "..." : "SOS"}</span>
                <span style={{ fontSize: 11, fontWeight: 400 }}>HELP ME</span>
              </button>
            </div>

            <div className="form-group" style={{ marginTop: 20 }}>
              <label className="form-label">Additional Message (optional)</label>
              <textarea
                id="sos-message"
                className="textarea"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                placeholder="e.g. Trapped in building, 3rd floor, injuries present"
                style={{ minHeight: 70 }}
              />
            </div>

            <div className="form-group grid-2" style={{ marginTop: 16 }}>
              <div>
                <label className="form-label">📷 Photo Proof</label>
                <input type="file" accept="image/*" onChange={handleImage} className="input" style={{ fontSize: 12 }} />
                {previews.image && <img src={previews.image} alt="Preview" className="img-preview" />}
              </div>
              <div>
                <label className="form-label">📹 Video Proof</label>
                <input type="file" accept="video/*" onChange={handleVideo} className="input" style={{ fontSize: 12 }} />
                {previews.video && <video src={previews.video} className="img-preview" controls />}
              </div>
            </div>
          </div>
        )}

        {/* SOS History with Timeline */}
        {history.length > 0 && (
          <div className="card" style={{ marginTop: 24 }}>
            <div className="card-header">
              <span className="card-title">Recent SOS History</span>
            </div>
            <div className="sos-timeline">
              {history.map((item) => {
                const step = statusStep[item.status] ?? 0;
                const isSpam = item.spamFlag || item.status === "spam";
                return (
                  <div key={item._id} className="sos-timeline-item" style={isSpam ? { opacity: 0.65, borderLeft: "2px solid var(--warning)" } : {}}>
                    <div className={`sos-timeline-dot ${item.status === "resolved" ? "complete" : isSpam ? "spam" : item.status === "active" ? "active" : "pending"}`} />
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                      <div>
                        <div style={{ fontSize: 13, fontWeight: 600 }}>
                          {item.location?.address || `${item.location?.lat?.toFixed(4)}, ${item.location?.lng?.toFixed(4)}`}
                        </div>
                        <div className="muted">{new Date(item.createdAt).toLocaleString()}</div>
                        {item.message && (
                          <div style={{ fontSize: 11, color: "var(--text-2)", marginTop: 4 }}>
                            {item.message.slice(0, 80)}{item.message.length > 80 ? "…" : ""}
                          </div>
                        )}
                        {item.dispatch?.teamName && !isSpam && (
                          <div style={{ fontSize: 11, marginTop: 4 }}>
                            Rescue team: <strong>{item.dispatch.teamName}</strong>
                            {item.dispatch.leadPhone ? (
                              <>
                                {" "}·{" "}
                                <a
                                  href={`tel:${item.dispatch.leadPhone.replace(/[^+\d]/g, '')}`}
                                  style={{ color: "var(--success)", fontWeight: 700 }}
                                >
                                  {item.dispatch.leadPhone}
                                </a>
                              </>
                            ) : null}
                          </div>
                        )}
                        {isSpam && item.spamReason && (
                          <div style={{ fontSize: 10, color: "var(--warning)", marginTop: 4, fontStyle: "italic" }}>
                            🛡️ {item.spamReason}
                          </div>
                        )}
                      </div>
                      <span
                        className="badge"
                        style={{
                          background: isSpam ? "rgba(245,158,11,0.15)" : `${statusColor[item.status]}22`,
                          color: isSpam ? "var(--warning)" : statusColor[item.status],
                        }}
                      >
                        {isSpam ? "🛡️ Flagged" : item.status}
                      </span>
                    </div>
                    {/* Mini status pipeline */}
                    {!isSpam && (
                      <div style={{ display: "flex", gap: 4, marginTop: 8 }}>
                        {statusLabels.map((label, i) => (
                          <div key={i} style={{
                            flex: 1, height: 3, borderRadius: 2,
                            background: i <= step ? statusColor[item.status] || "var(--primary)" : "var(--border)"
                          }} />
                        ))}
                      </div>
                    )}
                    {/* Inline review prompt for resolved SOS */}
                    {item.status === "resolved" && item.dispatch?.teamId && !reviewedSosIds.has(item._id) && (
                      <div style={{ marginTop: 12 }}>
                        <ReviewForm
                          teamId={item.dispatch.teamId}
                          teamName={item.dispatch.teamName}
                          sosId={item._id}
                          onSubmitted={() => setReviewedSosIds((prev) => new Set([...prev, item._id]))}
                        />
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Important note */}
        <div className="card" style={{
          marginTop: 20, background: "rgba(239,68,68,0.05)",
          border: "1px solid rgba(239,68,68,0.2)", textAlign: "center"
        }}>
          <p style={{ fontSize: 13, color: "var(--text-2)" }}>
            ⚠ For life-threatening emergencies, also call <strong style={{ color: "var(--danger)", fontSize: 16 }}>112</strong>
          </p>
        </div>
      </div>
    </PublicLayout>
  );
};

export default SOSPage;
